# Generated by Django 4.2.3 on 2023-09-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='numero',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='quartier',
            field=models.CharField(max_length=300, null=True, verbose_name='Quartier / ville'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='sexe',
            field=models.CharField(max_length=30, null=True, verbose_name='Genre'),
        ),
    ]
