# Generated by Django 4.2.3 on 2023-09-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_alter_utilisateur_date_naissance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='prenom',
        ),
    ]
