# Generated by Django 4.2.3 on 2023-11-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_remove_utilisateur_nom_remove_utilisateur_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='numero',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='quartier',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Quartier / ville'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='sexe',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='type_compte',
            field=models.CharField(choices=[('admin', 'Admin'), ('recruteur', 'Recruteur'), ('candidat', 'Candidat')], max_length=300),
        ),
    ]
