# Generated by Django 4.2.3 on 2023-09-07 10:22

from django.db import migrations, models
import django.db.models.deletion
import emploi.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('prenom', models.CharField(max_length=300)),
                ('sexe', models.CharField(max_length=30, verbose_name='Genre')),
                ('quartier', models.CharField(max_length=300, verbose_name='Quartier / ville')),
                ('date_naissance', models.DateField()),
                ('date_candidature', models.DateField(auto_now=True, verbose_name='Date de candidature')),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.CharField(max_length=200)),
                ('contacter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('priorite', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('date_limite', models.DateField(verbose_name='Date limite')),
                ('date', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to=emploi.models.get_file_path)),
                ('description', tinymce.models.HTMLField()),
                ('niveau_minimum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emploi.diplome', verbose_name='Diplome requis')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('document', models.FileField(upload_to=emploi.models.get_file_path)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.candidat')),
            ],
        ),
        migrations.AddField(
            model_name='candidat',
            name='dernier_diplome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emploi.diplome'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='emploi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emploi.emploi'),
        ),
    ]
