# Generated by Django 4.2.3 on 2023-11-09 09:52

import actualite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='image',
            field=models.ImageField(blank=True, upload_to=actualite.models.get_file_path, verbose_name='Image 1200x700'),
        ),
    ]
