# Generated by Django 4.2.3 on 2023-11-09 09:52

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=models.ImageField(upload_to=service.models.get_file_path, verbose_name='Image 500x500'),
        ),
    ]
