# Generated by Django 4.2.3 on 2023-11-09 10:16

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_categorie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to=service.models.get_file_path, verbose_name='Image 500x500'),
        ),
    ]
