# Generated by Django 4.2.3 on 2023-11-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='image',
            field=models.ImageField(upload_to='equipe/%Y/%m/%d', verbose_name='Image 500x500'),
        ),
    ]
