# Generated by Django 4.2.3 on 2023-09-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('email', models.EmailField(max_length=150)),
                ('sujet', models.CharField(max_length=150)),
                ('message', models.TextField(max_length=500)),
                ('repondu', models.BooleanField(default=False, verbose_name='Répondu')),
                ('reponse', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
