# Generated by Django 4.2.3 on 2023-09-07 10:21

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512, verbose_name='Question*')),
                ('reponse', tinymce.models.HTMLField(verbose_name='Reponse à la question*')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Question-question',
                'verbose_name_plural': 'Question-questions',
            },
        ),
    ]
