# Generated by Django 4.2.3 on 2023-09-07 10:21

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AProposModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to='image/%Y/%M/%d', verbose_name='Image de couverture *')),
                ('lienVideoYoutube', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Lien youtube de la video')),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'A propos de CAFE SARL',
                'verbose_name_plural': 'A propos de CAFE SARL',
            },
        ),
        migrations.CreateModel(
            name='PresentationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenue', tinymce.models.HTMLField(help_text="L'ancien s'il existe sera ecrasé \n il ne peut y avoir qu'une seule présentation", verbose_name='Présentation')),
                ('last_update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Présentation de CAFE SARL',
                'verbose_name_plural': 'Présentation de CAFE SARL',
            },
        ),
    ]
