# Generated by Django 4.2.3 on 2023-11-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aproposmodel',
            name='image',
            field=models.ImageField(upload_to='image/%Y/%M/%d', verbose_name='Image de couverture 1200x700'),
        ),
    ]
